# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-10 09:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0002_auto_20180109_1808'),
    ]

    operations = [
        migrations.AlterField(
            model_name='haribhaktdetail',
            name='mobile_no',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
