# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-01-12 06:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0003_auto_20180110_1506'),
    ]

    operations = [
        migrations.AlterField(
            model_name='karyakargroup',
            name='karyakar_from',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='karyakargroup',
            name='karyakar_to',
            field=models.DateField(blank=True),
        ),
    ]
